name: example
description: HeroAnimation example project.

publish_to: 'none'


version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: 0.1.4

  cupertino_icons: ^1.0.2
  hero_animation:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/